# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ff6be8f1b8d4f4259a4a5bca44af8976c1304733e7d9d72943151c88b5b5d84de184dc2534f8a0451835b067b68d3d1cc6bf7979808269746a5ea6bce6c93a1

test:
  secret_key_base: 4fff769cccc88234e2d9f90b381277a684da42003d46fec02b544113ec1640277cfa2d6408663593354ca2e3905e4b4c970dbf89b8c3c633c75dad0e17c0e7c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
